POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZmZvbnRpIiwiaWQiOiI2M2MxMzY0ZDE2YTExYTVkNWMzMjVhZjEiLCJpYXQiOjE2NzM2MTEwMTN9.MEIBwMjBk68RNxjdIcMcac0VnKKwia7WORAYSw504qw

{
  "url": "https://overreacted.io/things-i-dont-know-as-of-2018/",
  "title": "Things I don't know as of 2018",
  "author": "Dan Abramov"
}

###

POST https://bloglist.cyclic.app/api/blogs
Content-Type: application/json

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
}

###

curl --request POST \
    --url https://bloglist.cyclic.app/api/blogs \
    --header 'content-type: application/json' \
    --header 'user-agent: vscode-restclient' \
    --data '{"title": "Go To Statement Considered Harmful","author": "Edsger W. Dijkstra","url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"}'
