DELETE http://localhost:3003/api/blogs/63c169ced30ec1c8bd403749
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZmZvbnRpIiwiaWQiOiI2M2MxMzY0ZDE2YTExYTVkNWMzMjVhZjEiLCJpYXQiOjE2NzM2MTEwMTN9.MEIBwMjBk68RNxjdIcMcac0VnKKwia7WORAYSw504qw

###

DELETE https://bloglist.cyclic.app/api/blogs/63b95e3ecb4c6d786bd2c0bd

###

curl --request DELETE \
  --url https://bloglist.cyclic.app/api/blogs/63b95e3ecb4c6d786bd2c0bd \
  --header 'user-agent: vscode-restclient'
